export const BUSCAR = "BUSCAR";
export const BUSCAR_ID = "BUSCAR_ID";

export const BUSCAR_PROCESSO = "BUSCAR_PROCESSO";
export const BUSCAR_PROCESSO_ID = "BUSCAR_PROCESSO_ID";
export const ADICIONAR_PROCESSO = "ADICIONAR_PROCESSO";
export const ATUALIZAR_PROCESSO = "ATUALIZAR_PROCESSO";
export const REMOVER_PROCESSO = "REMOVER_PROCESSO";
